name: Trigger test suite for the project

on:
  pull_request:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests with coverage reporting
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up go
        id: go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download dependencies
        if: ${{ steps.go.outputs.cache-hit != 'true' }}
        run: go mod download

      - name: Run tests with coverage
        run: go test ./... -v --race --covermode=atomic --coverprofile=coverage.out

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
          name: ${{ github.event.repository.name }}
          token: ${{ secrets.CI_CODECOV_TOKEN }}
